on:
  push:
  pull_request:

jobs:
  check_syntax:
    name: Check syntax
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build avatar
        run: nix develop --command python build.py
      - name: Zip build output
        run: env -C build zip -r ../build.zip .
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: build.zip
