on:
  push:
  pull_request:

jobs:
  check_syntax:
    name: Check syntax
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - name: Checkout
        uses: actions/checkout@v3
      - uses: workflow/nix-shell-action@v3
        with:
          flakes-from-devshell: true
          script: |
            python build.py
